CREATE DATABASE IF NOT EXISTS Users; 

CREATE TABLE Users.Users (
	user_id = INTEGER AUTO_INCREMENT PRIMARY KEY,
    first_name = VARCHAR(255) NOT NULL,
    last_name = VARCHAR(255) NOT NULL, 
	dob = DATE NOT NULL, 
    phone = VARCHAR(50) NOT NULL
); 

